### ISSUE TITLE
Local random source being tainted with non-random values

### ISSUE THREAD

**Issue by HacKanCuBa** [RandomSanityProject/randomsanity_debian#1]
At line [60](https://github.com/RandomSanityProject/randomsanity_debian/blob/master/randomsanity#L60), the whole response, which contain non-random values, is written to `/dev/urandom`.

Also, another bug prevents getting the response correctly (see issue #2 ).

An example response is the following:

```
HTTP/1.1 200 OK
Content-Type: application/json
X-Entropy: 89f4f79ca1c0079d6f6324ead4ff522939a425bb232c8fdfdd1b8f7447a71d83
X-Cloud-Trace-Context: 408cbcabc537219ef96f45393b4cd527;o=1
Date: Tue, 02 May 2017 12:10:50 GMT
Server: Google Frontend
Content-Length: 4

true
```

Only `X-Entropy` should be used, not the entire response. I might submit a patch for this.

**Comment by gavinandresen** [comment]
Mixing in non-random input doesn't hurt, but I agree it looks better to only add the X-Entropy.

My only concern with your fix is if it adds extra dependencies; is 'cut' part of the base debian/ubuntu install? If it is not, is shasum ?  (I thought about piping ${RESPONSE[*]} | shasum -a 256 >> /dev/urandom)

**Comment by HacKanCuBa** [comment]
Using `shasum` might work, but it's kinda dirty, because there's still non-random values being mixed with random ones, where the ones that matter are this last ones.

`cut` is part of GNU Coreutils, which I think is in every distro. `sha256sum` is also part of that package, and a better choice than `shasum` which might not be everywhere.

**Comment by HacKanCuBa** [comment]
I was thinking that we should also convert from hex to bin prior pushing into urandom.

**Comment by gavinandresen** [comment]
Again, adding non-randomness to /dev/urandom does no harm (it does no good, either).  But I think this will come up again and again if we DON'T convert just X-Entropy to binary and write that to /dev/urandom, so I'm all for doing that.
