### ISSUE TITLE
Typo prevents getting the response right

### ISSUE THREAD

**Issue by HacKanCuBa** [RandomSanityProject/randomsanity_debian#2]
There's a typo in line [34](https://github.com/RandomSanityProject/randomsanity_debian/blob/master/randomsanity#L34) where double-quotes are missing.

The line reads: `RESPONSE=( $(wget --quiet --tries=1 --output-document=- --timeout=5 --max-redirect=1 --save-headers "$URL" ) )`

And it should be: `RESPONSE=( "$(wget --quiet --tries=1 --output-document=- --timeout=5 --max-redirect=1 --save-headers "$URL" )" )`

Without the double-quotes, the response looks like: `trueent-Length: 4ontend12:03:42 GMTeaa9484a68833337603d;o=1216a94e62651272b`

With double-quotes, the response is correct:

```
HTTP/1.1 200 OK
Content-Type: application/json
X-Entropy: 89f4f79ca1c0079d6f6324ead4ff522939a425bb232c8fdfdd1b8f7447a71d83
X-Cloud-Trace-Context: 408cbcabc537219ef96f45393b4cd527;o=1
Date: Tue, 02 May 2017 12:10:50 GMT
Server: Google Frontend
Content-Length: 4

true
```

*Note that those are different requests*

**Comment by HacKanCuBa** [comment]
My bad, double-quotes makes it a single element array.
The correct fix is: `IFS=$'\n' RESPONSE=( $(wget --quiet --tries=1 --output-document=- --timeout=5 --max-redirect=1 --save-headers "$URL" ) )`

**Comment by gavinandresen** [comment]
What version of Linux/bash?  Works for me with or without the IFS= line on Ubuntu 14.04 / bash 4.3.11

Explicitly setting IFS seems like a good thing to do, though.

**Comment by HacKanCuBa** [comment]
```
:~$ uname -a
Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux

:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch

:~$ bash --version
GNU bash, version 4.4.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
